[build]
  publish = "."

[[redirects]]
  from = "/adminpanelconfig"
  to = "/adminpanelconfig.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/topup"
  to = "/topup.html"
  status = 200

[[redirects]]
  from = "/payment-instruction"
  to = "/payment-instruction.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
